### ISSUE TITLE
doesn't work in test app

### ISSUE THREAD

**Issue by bgrayburn** [bgrayburn/meteor-processing-js#1]

**Comment by dennisharrison** [comment]
```bash
W20150214-10:57:07.402(-6)? (STDERR)
W20150214-10:57:07.402(-6)? (STDERR) /Users/dennisharrison/.meteor/packages/meteor-tool/.1.0.40.6jkhle++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150214-10:57:07.402(-6)? (STDERR) 						throw(ex);
W20150214-10:57:07.402(-6)? (STDERR) 						      ^
W20150214-10:57:07.408(-6)? (STDERR) ReferenceError: navigator is not defined
W20150214-10:57:07.408(-6)? (STDERR)     at Object../src/ (packages/bgrayburn:processingjs/processing.min.js:1:1)
W20150214-10:57:07.408(-6)? (STDERR)     at h (packages/bgrayburn:processingjs/processing.min.js:1:1)
W20150214-10:57:07.408(-6)? (STDERR)     at e$$0 (packages/bgrayburn:processingjs/processing.min.js:1:1)
W20150214-10:57:07.409(-6)? (STDERR)     at Package (packages/bgrayburn:processingjs/processing.min.js:1:1)
W20150214-10:57:07.409(-6)? (STDERR)     at /Users/dennisharrison/projects/mapp-skeletor/app/.meteor/local/build/programs/server/packages/bgrayburn_processingjs.js:451:4
W20150214-10:57:07.409(-6)? (STDERR)     at /Users/dennisharrison/projects/mapp-skeletor/app/.meteor/local/build/programs/server/packages/bgrayburn_processingjs.js:458:3
W20150214-10:57:07.409(-6)? (STDERR)     at /Users/dennisharrison/projects/mapp-skeletor/app/.meteor/local/build/programs/server/boot.js:205:10
W20150214-10:57:07.409(-6)? (STDERR)     at Array.forEach (native)
W20150214-10:57:07.409(-6)? (STDERR)     at Function._.each._.forEach (/Users/dennisharrison/.meteor/packages/meteor-tool/.1.0.40.6jkhle++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150214-10:57:07.409(-6)? (STDERR)     at /Users/dennisharrison/projects/mapp-skeletor/app/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by bgrayburn** [comment]
Taking a look shortly, thanks for pointing this out

**Comment by dennisharrison** [comment]
It looks like all you need to do is update your package.js

```javascript
Package.onUse(function (api) {
  api.versionsFrom("1.0");
  api.addFiles(['client/processing.min.js'], ['client']);
});
```

**Comment by bgrayburn** [comment]
pushed to master. tiny test passing. thank you Dennis!

**Comment by dennisharrison** [comment]
Thanks for the package.  Now all I have to do is learn processing :)

**Comment by srinivasmangipudi** [comment]
I am still getting the same error.

 "Navigator is not defined"
